import pathlib

from pymeta import Tokens


def is_ident_start(string: str) -> bool: ...


def is_ident_continue(string: str) -> bool: ...


class Span:
    """See: https://doc.rust-lang.org/proc_macro/struct.Span.html"""

    @staticmethod
    def call_site() -> Span: ...

    @staticmethod
    def mixed_site() -> Span: ...

    def start(self) -> Span: ...

    def end(self) -> Span: ...

    def line(self) -> int: ...

    def column(self) -> int: ...

    def file(self) -> str: ...

    def local_file(self) -> pathlib.Path | None: ...

    def resolved_at(self, other: Span) -> Span: ...

    def located_at(self, other: Span) -> Span: ...

    def source_text(self) -> str | None: ...

    def __repr__(self) -> str: ...


class TokenStream:
    def append_group(self, delimiter: str, tokens: TokenStream, span: Span | None): ...

    def append_punct(self, char: str, spacing: str, span: Span | None): ...

    def append_ident(self, string: str, span: Span | None): ...

    def append_int_literal(self, value: int, suffix: str | None, span: Span | None): ...

    def append_float_literal(self, value: float, suffix: str | None, span: Span | None): ...

    def append_str_literal(self, type: str, value: str, span: Span | None): ...

    def append_bytes_literal(self, type: bytes, value: str, span: Span | None): ...

    def to_pymeta_tokens(self) -> Tokens: ...

    @staticmethod
    def parse(source_code: str) -> TokenStream: ...


def tracked_path(path: pathlib.Path) -> None: ...


def tracked_env_var(key: str) -> str: ...
