def is_ident_start(string: str) -> bool: ...

def is_ident_continue(string: str) -> bool: ...

class Span:
    @staticmethod
    def call_site() -> Span: ...

    def __repr__(self) -> str: ...

class TokenStream:
    def append_group(self, delimiter: str, tokens: TokenStream, span: Span | None): ...

    def append_punct(self, char: str, spacing: str, span: Span | None): ...

    def append_ident(self, string: str, span: Span | None): ...

    def append_int_literal(self, value: int, suffix: str | None, span: Span | None): ...

    def append_float_literal(self, value: float, suffix: str | None, span: Span | None): ...

    def append_str_literal(self, type: str, value: str, span: Span | None): ...

    def append_bytes_literal(self, type: bytes, value: str, span: Span | None): ...
