name: Tests
on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - mode: 'coverage'
            toolchain: nightly
            features: '--features "dump_source_on_error"'
          - mode: '~'
            toolchain: stable
            features: '--features "dump_source_on_error"'
          - mode: 'msrv'
            toolchain: stable
            features: ''
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
      - uses: astral-sh/setup-uv@v8.3.2
      - name: Init CPython venv
        working-directory: tests/cpython_env
        run: uv sync
      - name: Install cargo tools
        uses: taiki-e/install-action@v2
        with: 
          tool: |
            ${{ matrix.mode == 'coverage' && 'cargo-llvm-cov' || '' }}
            ${{ matrix.mode == 'msrv' && 'cargo-msrv' || '' }}
      
      - name: Run tests${{ matrix.mode == 'coverage' && ' with llvm-cov' || '' }}${{ matrix.mode == 'msrv' && ' with cargo-msrv' || '' }}
        run: |
          source ./tests/cpython_env/.venv/bin/activate
          export LD_LIBRARY_PATH="$(python -c 'import sysconfig; print(sysconfig.get_config_var("LIBDIR"))'):$LD_LIBRARY_PATH"
          echo "$LD_LIBRARY_PATH"
          
          cargo \
          ${{ matrix.mode == 'coverage' && 'llvm-cov --lcov --output-path lcov.info' || ''}} \
          ${{ matrix.mode == 'msrv' && 'msrv verify -- cargo' || '' }} \
          test --package pymeta-proc-macro-backend \
          ${{ matrix.features }} \
          --tests -- --test-threads=1
      
      - name: Upload to Codecov
        if: ${{ matrix.mode == 'coverage' }}
        uses: codecov/codecov-action@v7
        with: 
          files: lcov.info
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}