name: Tests
on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - toolchain: nightly
            features: '--features "dump_source_on_error"'
            coverage: true
          - toolchain: stable
            features: '--features "dump_source_on_error"'
            coverage: false
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
      - uses: astral-sh/setup-uv@v8.3.2
      - name: Init CPython venv
        working-directory: tests/cpython_env
        run: uv sync
      - name: Install cargo-llvm-cov
        if: ${{ matrix.toolchain == 'nightly' }}
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Run tests ${{ matrix.coverage && 'with llvm-cov' || '' }}
        run: |
          source ./tests/cpython_env/.venv/bin/activate
          export LD_LIBRARY_PATH="$(dirname "$(python -c 'import sysconfig; print(sysconfig.get_config_var("LIBDIR"))')"):$LD_LIBRARY_PATH"
          
          cargo \
          ${{ matrix.coverage && 'llvm-cov --lcov --output-path lcov.info' || ''}} \
          test --package pymeta-proc-macro-backend \
          ${{ matrix.features }} \
          --tests -- --test-threads=1
      - name: Upload to Codecov
        run: echo TODO